### ISSUE TITLE
How do I get the key once it is generated?

### ISSUE THREAD

**Issue by tahmidkhan** [ekonstantinidis/django-rest-framework-api-key#6]
I am not sure if this is included somewhere, but after creating an API key from the admin panel, how do I actually get the key so that I can put it in my headers? Its always hidden for me.

**Comment by manosim** [comment]
Hello @tahmidkhan once you click save (when creating a key) it will show up in the next page, above the "Success" message. If you missed it, you can still access it from the database or running the django shell command(import the library, select the model etc). I am attaching a screenshot - hope it helps!

![screen shot 2017-01-03 at 18 32 37](https://cloud.githubusercontent.com/assets/6333409/21618524/3bd7c39a-d1e3-11e6-8433-4fad04f1fa13.png)

**Comment by tahmidkhan** [comment]
@manosim Oh good stuff, now I got it. I missed the message popping up. Thanks a lot, this is really helpful.
