### ISSUE TITLE
Benefits over token authentication?

### ISSUE THREAD

**Issue by hermanocabral** [ekonstantinidis/django-rest-framework-api-key#7]
Hi,

Just wondering why would I use this instead of DRF's token auth?

**Comment by swapnilsm** [comment]
Because then you will need a service user to be created for this. And that is an overkill because it's a service which will be accessing those apis and not a user.

**Comment by adrianboyko** [comment]
Hashing the key before saving it would be another handy advantage over DRF's authtoken, if implemented.
